# Generated by Django 2.2.2 on 2019-06-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_menu_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dish',
            new_name='desh',
        ),
        migrations.AddField(
            model_name='order',
            name='totle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='dish',
            field=models.TextField(),
        ),
    ]
