# Generated by Django 2.2.2 on 2019-06-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190606_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='desh',
        ),
        migrations.AddField(
            model_name='menu',
            name='desh',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='order.order'),
        ),
    ]
